# Generated by Django 3.2.13 on 2022-11-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltw_btl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('sgk', 'Sach giao khoa'), ('tth', 'Tieu thuyet'), ('trtr', 'Truyen tranh')], default='sgk', max_length=200, null=True)),
                ('release_date', models.DateTimeField(max_length=200, null=True)),
                ('number_of_pages', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[(1, 'Nam'), (0, 'Nu')], default=1, max_length=100, null=True),
        ),
    ]
