# Generated by Django 3.2.13 on 2022-11-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltw_btl', '0002_auto_20221127_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Sách Giáo Khoa', 'Sach giao khoa'), ('Tiểu Thuyết', 'Tieu thuyet'), ('Truyện Tranh', 'Truyen tranh')], default='sgk', max_length=200, null=True),
        ),
    ]
