# Generated by Django 3.2.13 on 2022-11-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltw_btl', '0003_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
