# Generated by Django 3.2.13 on 2022-11-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltw_btl', '0005_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Sách Giáo Khoa', 'Sách Giáo Khoa'), ('Tiểu Thuyết', 'Tiểu Thuyết'), ('Truyện Tranh', 'Truyện Tranh')], default='sgk', max_length=200, null=True),
        ),
    ]
